name: myHR Gradle Test

on:
  pull_request:
    branches: [ main, master ]    # main 브랜치에 PR 보낼 때 실행
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
        # Branch Checkout
      - name: Checkout Branch
        uses: actions/checkout@v3

        # JDK 17 Setup
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

        # Gradle Wrapper 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradle

        # Gradle Cache Setting
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev' }}

        # Execute Test
      - name: Test with Gradle
        run: ./gradlew --info test

        # Generate Test Result Report
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: 'build/test-results/**/*.xml'

        # Generate Test Fail Result Report
      - name: If the test fails, register a check comment in the failed code line
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'build/test-results/**/*.xml'
          token: ${{ github.token }}